Feat: Add wash_trade.py #19
our-ml-flow/data_pipeline pull request #20
Opened 2023-08-18 11:14 UTC by DataHyeon

## Overview
- Add new pipeline about wash trade

## Change Log
- mart/wash_trade.py

## Issue Tags
- #19

2023-08-18 21:30 UTC, Jinlee057 requested changes
리뷰 완료했습니다
크론 스케쥴 수정가능여부 확인부탁드립니다

2023-08-18 21:30 UTC, Jinlee057 commented on flow/mart/wash_trade.py
> +        schedule=(CronSchedule(cron="0 11 1 * *", timezone="Asia/Seoul"))
아침 10시반 듄쿼리 데이터 이후 듄쿼링 + 블랙리스트 자료로 지갑 데이터 적재를 11시 진행예정입니다.
블랙리스트 작업은 월에 한 번이긴 하지만 11시로 시간이 겹쳐도 문제가 없을까요?
블랙리스트 소요 시간이 10분 이내라면 혹시 10시 50분 쯤으로 변경 가능하실까요?

2023-08-18 21:30 UTC, Jinlee057 commented on flow/mart/wash_trade_test.py
테스트파일도 업로드 하시는건가요?

2023-08-18 21:30 UTC, Jinlee057 commented on module/mart/wash_trade_monthly/task/load_task.py
> +            wash_trade_df.to_sql("wash_trade_wallet_month_test", engine, if_exists='append', index=False)
db 적재시 사용되는 이름에 그대로 test 두어도 괜찮을까요?

2023-08-18 21:30 UTC, Jinlee057 commented on module/mart/wash_trade_monthly/task/load_task.py
> +        wash_trade_df = pd.read_sql(query, engine)
해당월의 데이터가 db서버에 있는지 먼저 확인하는 내용인가요?
try: 해당월 데이터 db서버내 존재 여부 확인
except 에러 발생시 처리
exept 자료가 없다면 동작할 해롱
   try: 생성된 데이터 보내기
  except: 에러 발생시 처리

이 구조로 이해하면 될까요?

2023-08-19 02:34 UTC, kangsumin2ya approved these changes
확인했습니다!

2023-08-19 09:07 UTC, DataHyeon commented on module/mart/wash_trade_monthly/task/load_task.py
> +        wash_trade_df = pd.read_sql(query, engine)
이미 앞의 월 데이터가 있기 때문에 따로 확인하는 코드는 아니고
해당 데이터를 가져올 때 문제가 생기면 except처리를 해주는 부분입니다.

2023-08-19 09:08 UTC, DataHyeon commented on module/mart/wash_trade_monthly/task/load_task.py
> +            wash_trade_df.to_sql("wash_trade_wallet_month_test", engine, if_exists='append', index=False)
교체 했습니다

2023-08-19 09:45 UTC, DataHyeon commented on flow/mart/wash_trade.py
> +        schedule=(CronSchedule(cron="0 11 1 * *", timezone="Asia/Seoul"))
10시 40분으로 바꿨습니다.

2023-08-19 09:45 UTC, DataHyeon commented on flow/mart/wash_trade_test.py
삭제 예정입니다.

2023-08-19 10:00 UTC, kangsumin2ya approved these changes
고생하셨습니다!!

2023-08-19 10:22 UTC, Jinlee057 approved these changes
넵 수정내역 확인했습니다!

2023-08-19 12:46 UTC, merged